# Start the service with the command 'docker-compose up -d'

#version: '3.9'

services:
  slp-db:
    build: ./slp-db
    container_name: slp-db
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    #mem_limit: 500mb
    #links:
    #  - mongo-slp-indexer
    ports:
      - '5020:5020' # <host port>:<container port>
    volumes:
      - ../data/ipfsdata:/home/safeuser/psf-slp-db/.ipfsdata
      - ../data/leveldb:/home/safeuser/psf-slp-db/leveldb
      - ./slp-db/start-slp-db.sh:/home/safeuser/psf-slp-db/start-slp-db.sh
    restart: always

  tx-indexer:
    build: ./tx-indexer
    container_name: tx-indexer
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    ports:
      - '5454:5454' # <host port>:<container port>
    volumes:
      - ./tx-indexer/start-tx-indexer.sh:/home/safeuser/psf-slp-indexer-g2/start-tx-indexer.sh
    restart: always

  block-indexer:
    build: ./block-indexer
    container_name: block-indexer
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    volumes:
      - ./block-indexer/start-block-indexer.sh:/home/safeuser/psf-slp-indexer-g2/start-block-indexer.sh
    restart: always